### ISSUE TITLE
Hi! I had an idea for a mod that would pair GREAT with your Pierre MAY Plan Ahead! Looking for advice..

### ISSUE THREAD

**Issue by DucksonFleet** [LenneDalben/StardewValleyMods#1]
Hello Lenne, 

Thank you for making some of my favorite mods to play with. They've really brought me more joy to the game. :) I wanted to make a mod that sent the PC a mail from the Governor, informing us that the market has been hit hard with the exit of joja corp, and that certain crops must be levied to balance market distrobution. This mod would pick a few random crops each season and lower their profit margins by at least 70%. It could also impact artisanal and animal products as well. I think this could pair very nicely with Pierre May Plan Ahead (using the draylon edition and loving it!). I even saw your new Quest mod and thought that it would help to balance the player's economy by giving them something to do with certain products, like making a cooked dish out of them, even if they are levied that season. 

I'm able to make a mail using MFM but I'm having trouble finding out how to make the crops to be levied random. If there's any advice you can give, I would greatly appreciate it. :3

**Comment by LenneDalben** [comment]
Hi DucksonFleet,

Thank you for your kind words! I'm glad you've enjoyed my mods :3 

I saw your mod idea in the [mod ideas list](https://github.com/StardewModders/mod-ideas/issues/508), exciting stuff! I concur with minervamaga's tag that your idea is a C# SMAPI mod. For Pierre Plans Ahead and Artisan Equipment for Sale, I was able to use Shop Tile Framework (STF), so I could tell you that *technically* you could use STF to do it, but you'd have to recreate the shop inventory and use either the random or seeded random condition checks in STF, which would be a lot of redundant work and it would be faster and less tedious for you to go the C# SMAPI mod route.

You'd need to know the basics of C# (Jonqora has recommended SoloLearn, which is a site-that also has a mobile app-that has interactive tutorials), and then set up the necessary software to start a C# mod. The SDV wiki has a guide [here](https://stardewvalleywiki.com/Modding:Modder_Guide/Get_Started). You'd also need to [decompile the game](https://stardewvalleywiki.com/Modding:Modder_Guide/Get_Started#Decompile_the_game_code) to then make the mod. I know Chronicler Cherry has offered to help me with a different SMAPI mod idea I have related to the shops, so you could try reaching out to them on the #making-mods channel, once you know the basics of C# and are ready to go for it (if you already do, then you're in better shape than I am! I'm still working through that tutorial so I won't be able to provide much technical assistance haha). One thing you can do in the meantime, if you're a planner like me, is bust out a table (or text file, whatever works for you :) ) with details on which crops you're looking to alter, how much the profit margins will be hit, and note down any other ideas you have, like if it's a seasonal thing or not.

I hope this helps!

**Comment by DucksonFleet** [comment]
Perhaps instead of STF, because I don't really need to edit the shops, I can use Content Patcher and make it a content pack? I see its capable of a randomizer as well. A content pack coupled with MFM could technically do the job perhaps? I just started reading up on c# ^-^'

**Comment by LenneDalben** [comment]
As we discussed in the SDV Discord, Content Patcher (CP) would only affect newly spawned crops, and not existing ones (which players may have in chests or in their inventory), so you'd still need a C# SMAPI mod. Note that if you do go the C# SMAPI mod route, you could actually integrate mail as part of it and not need the Mail Framework Mod (MFM) component, although you can certainly keep it! :)
